services:
  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgadmin
    hostname: pgadmin
    ports:
      - "${PGADMIN_PUBLISH_PORT:-5050}:80"
    env_file:
      - ./pgadmin/.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - docker-dev-common
    restart: no

volumes:
  pgadmin_data:

networks:
  docker-dev-common:
    external: true