services:
  elasticsearch:
    image: elasticsearch:9.3.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ./elasticsearch/.env
    ports:
      - "${ELASTICSEARCH_PUBLISH_PORT}:${ELASTICSEARCH_DEFAULT_PORT}"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - docker-dev-common
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: no

  kibana:
    image: kibana:9.3.0
    container_name: kibana
    hostname: kibana
    env_file:
      - ./elasticsearch/.env
    ports:
      - "${KIBANA_PUBLISH_PORT}:${KIBANA_DEFAULT_PORT}"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - docker-dev-common
    restart: no

volumes:
  elasticsearch_data:

networks:
  docker-dev-common:
    external: true
